# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: libresvip_tauri.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from . import libresvip_tauri_pb2 as libresvip__tauri__pb2


class Conversion(Protocol):
    async def plugin_infos(self, request: libresvip__tauri__pb2.PluginInfosRequest, ctx: RequestContext) -> libresvip__tauri__pb2.PluginInfosResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def convert(self, request: libresvip__tauri__pb2.ConversionRequest, ctx: RequestContext) -> AsyncIterator[libresvip__tauri__pb2.SingleConversionResult]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def version(self, request: libresvip__tauri__pb2.VersionRequest, ctx: RequestContext) -> libresvip__tauri__pb2.VersionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    def move_file(self, request: libresvip__tauri__pb2.MoveFileRequest, ctx: RequestContext) -> AsyncIterator[libresvip__tauri__pb2.MoveFileResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ConversionASGIApplication(ConnectASGIApplication[Conversion]):
    def __init__(self, service: Conversion | AsyncGenerator[Conversion], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/LibreSVIP.Conversion/PluginInfos": Endpoint.unary(
                    method=MethodInfo(
                        name="PluginInfos",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.PluginInfosRequest,
                        output=libresvip__tauri__pb2.PluginInfosResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.plugin_infos,
                ),
                "/LibreSVIP.Conversion/Convert": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Convert",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.ConversionRequest,
                        output=libresvip__tauri__pb2.SingleConversionResult,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.convert,
                ),
                "/LibreSVIP.Conversion/Version": Endpoint.unary(
                    method=MethodInfo(
                        name="Version",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.VersionRequest,
                        output=libresvip__tauri__pb2.VersionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.version,
                ),
                "/LibreSVIP.Conversion/MoveFile": Endpoint.server_stream(
                    method=MethodInfo(
                        name="MoveFile",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.MoveFileRequest,
                        output=libresvip__tauri__pb2.MoveFileResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.move_file,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/LibreSVIP.Conversion"


class ConversionClient(ConnectClient):
    async def plugin_infos(
        self,
        request: libresvip__tauri__pb2.PluginInfosRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> libresvip__tauri__pb2.PluginInfosResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PluginInfos",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.PluginInfosRequest,
                output=libresvip__tauri__pb2.PluginInfosResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def convert(
        self,
        request: libresvip__tauri__pb2.ConversionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[libresvip__tauri__pb2.SingleConversionResult]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Convert",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.ConversionRequest,
                output=libresvip__tauri__pb2.SingleConversionResult,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def version(
        self,
        request: libresvip__tauri__pb2.VersionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> libresvip__tauri__pb2.VersionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Version",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.VersionRequest,
                output=libresvip__tauri__pb2.VersionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def move_file(
        self,
        request: libresvip__tauri__pb2.MoveFileRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[libresvip__tauri__pb2.MoveFileResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="MoveFile",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.MoveFileRequest,
                output=libresvip__tauri__pb2.MoveFileResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class ConversionSync(Protocol):
    def plugin_infos(self, request: libresvip__tauri__pb2.PluginInfosRequest, ctx: RequestContext) -> libresvip__tauri__pb2.PluginInfosResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def convert(self, request: libresvip__tauri__pb2.ConversionRequest, ctx: RequestContext) -> Iterator[libresvip__tauri__pb2.SingleConversionResult]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def version(self, request: libresvip__tauri__pb2.VersionRequest, ctx: RequestContext) -> libresvip__tauri__pb2.VersionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def move_file(self, request: libresvip__tauri__pb2.MoveFileRequest, ctx: RequestContext) -> Iterator[libresvip__tauri__pb2.MoveFileResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ConversionWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ConversionSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/LibreSVIP.Conversion/PluginInfos": EndpointSync.unary(
                    method=MethodInfo(
                        name="PluginInfos",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.PluginInfosRequest,
                        output=libresvip__tauri__pb2.PluginInfosResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.plugin_infos,
                ),
                "/LibreSVIP.Conversion/Convert": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Convert",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.ConversionRequest,
                        output=libresvip__tauri__pb2.SingleConversionResult,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.convert,
                ),
                "/LibreSVIP.Conversion/Version": EndpointSync.unary(
                    method=MethodInfo(
                        name="Version",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.VersionRequest,
                        output=libresvip__tauri__pb2.VersionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.version,
                ),
                "/LibreSVIP.Conversion/MoveFile": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="MoveFile",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.MoveFileRequest,
                        output=libresvip__tauri__pb2.MoveFileResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.move_file,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/LibreSVIP.Conversion"


class ConversionClientSync(ConnectClientSync):
    def plugin_infos(
        self,
        request: libresvip__tauri__pb2.PluginInfosRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> libresvip__tauri__pb2.PluginInfosResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PluginInfos",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.PluginInfosRequest,
                output=libresvip__tauri__pb2.PluginInfosResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def convert(
        self,
        request: libresvip__tauri__pb2.ConversionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[libresvip__tauri__pb2.SingleConversionResult]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Convert",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.ConversionRequest,
                output=libresvip__tauri__pb2.SingleConversionResult,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def version(
        self,
        request: libresvip__tauri__pb2.VersionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> libresvip__tauri__pb2.VersionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Version",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.VersionRequest,
                output=libresvip__tauri__pb2.VersionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def move_file(
        self,
        request: libresvip__tauri__pb2.MoveFileRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[libresvip__tauri__pb2.MoveFileResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="MoveFile",
                service_name="LibreSVIP.Conversion",
                input=libresvip__tauri__pb2.MoveFileRequest,
                output=libresvip__tauri__pb2.MoveFileResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
