# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: libresvip_tauri.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable
from typing import Protocol

from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import RequestContext
from connectrpc.server import (
    ConnectASGIApplication,
    Endpoint,
)

from . import libresvip_tauri_pb2 as libresvip__tauri__pb2


class Conversion(Protocol):
    async def plugin_infos(self, request: libresvip__tauri__pb2.PluginInfosRequest, ctx: RequestContext) -> libresvip__tauri__pb2.PluginInfosResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def convert(self, request: libresvip__tauri__pb2.ConversionRequest, ctx: RequestContext) -> AsyncIterator[libresvip__tauri__pb2.SingleConversionResult]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def version(self, request: libresvip__tauri__pb2.VersionRequest, ctx: RequestContext) -> libresvip__tauri__pb2.VersionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def move_file(self, request: libresvip__tauri__pb2.MoveFileRequest, ctx: RequestContext) -> AsyncIterator[libresvip__tauri__pb2.MoveFileResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ConversionASGIApplication(ConnectASGIApplication[Conversion]):
    def __init__(self, service: Conversion | AsyncGenerator[Conversion], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/LibreSVIP.Conversion/PluginInfos": Endpoint.unary(
                    method=MethodInfo(
                        name="PluginInfos",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.PluginInfosRequest,
                        output=libresvip__tauri__pb2.PluginInfosResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.plugin_infos,
                ),
                "/LibreSVIP.Conversion/Convert": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Convert",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.ConversionRequest,
                        output=libresvip__tauri__pb2.SingleConversionResult,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.convert,
                ),
                "/LibreSVIP.Conversion/Version": Endpoint.unary(
                    method=MethodInfo(
                        name="Version",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.VersionRequest,
                        output=libresvip__tauri__pb2.VersionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.version,
                ),
                "/LibreSVIP.Conversion/MoveFile": Endpoint.server_stream(
                    method=MethodInfo(
                        name="MoveFile",
                        service_name="LibreSVIP.Conversion",
                        input=libresvip__tauri__pb2.MoveFileRequest,
                        output=libresvip__tauri__pb2.MoveFileResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.move_file,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/LibreSVIP.Conversion"
