# Generated from libresvip_tauri.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.0 with parameter "protobuf=py,io=async".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, Endpoint

from .libresvip_tauri_pb import ConversionRequest, MoveFileRequest, MoveFileResponse, PluginInfosRequest, PluginInfosResponse, SingleConversionResult, VersionRequest, VersionResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor
    from connectrpc.request import Headers, RequestContext


class Conversion(Protocol):
    async def plugin_infos(self, request: PluginInfosRequest, ctx: RequestContext[PluginInfosRequest, PluginInfosResponse]) -> PluginInfosResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def convert(self, request: ConversionRequest, ctx: RequestContext[ConversionRequest, SingleConversionResult]) -> AsyncIterator[SingleConversionResult]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def version(self, request: VersionRequest, ctx: RequestContext[VersionRequest, VersionResponse]) -> VersionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def move_file(self, request: MoveFileRequest, ctx: RequestContext[MoveFileRequest, MoveFileResponse]) -> AsyncIterator[MoveFileResponse]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ConversionASGIApplication(ConnectASGIApplication[Conversion]):
    def __init__(
        self,
        service: Conversion | AsyncGenerator[Conversion],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/LibreSVIP.Conversion/PluginInfos": Endpoint.unary(
                    method=MethodInfo(
                        name="PluginInfos",
                        service_name="LibreSVIP.Conversion",
                        input=PluginInfosRequest,
                        output=PluginInfosResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.plugin_infos,
                ),
                "/LibreSVIP.Conversion/Convert": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Convert",
                        service_name="LibreSVIP.Conversion",
                        input=ConversionRequest,
                        output=SingleConversionResult,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.convert,
                ),
                "/LibreSVIP.Conversion/Version": Endpoint.unary(
                    method=MethodInfo(
                        name="Version",
                        service_name="LibreSVIP.Conversion",
                        input=VersionRequest,
                        output=VersionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.version,
                ),
                "/LibreSVIP.Conversion/MoveFile": Endpoint.server_stream(
                    method=MethodInfo(
                        name="MoveFile",
                        service_name="LibreSVIP.Conversion",
                        input=MoveFileRequest,
                        output=MoveFileResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.move_file,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/LibreSVIP.Conversion"


class ConversionClient(ConnectClient):
    async def plugin_infos(
        self,
        request: PluginInfosRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PluginInfosResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PluginInfos",
                service_name="LibreSVIP.Conversion",
                input=PluginInfosRequest,
                output=PluginInfosResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def convert(
        self,
        request: ConversionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[SingleConversionResult]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Convert",
                service_name="LibreSVIP.Conversion",
                input=ConversionRequest,
                output=SingleConversionResult,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def version(
        self,
        request: VersionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> VersionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Version",
                service_name="LibreSVIP.Conversion",
                input=VersionRequest,
                output=VersionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def move_file(
        self,
        request: MoveFileRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> AsyncIterator[MoveFileResponse]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="MoveFile",
                service_name="LibreSVIP.Conversion",
                input=MoveFileRequest,
                output=MoveFileResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
