# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: libresvip.proto
# plugin: python-aristaproto
# This file has been @generated
__all__ = (
    "PluginCategory",
    "ConversionMode",
    "ConflictPolicy",
    "PluginInfo",
    "PluginInfosRequest",
    "PluginInfosResponse",
    "ConversionGroup",
    "ConversionRequest",
    "SingleConversionResult",
    "VersionInfo",
    "MoveFileRequest",
    "MoveFileResponse",
    "ConversionBase",
)

from typing import (
    TYPE_CHECKING,
    AsyncIterator,
)
import aristaproto
import grpclib
from aristaproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import dataclass
if TYPE_CHECKING:
    import grpclib.server

class PluginCategory(aristaproto.Enum):
    INPUT = 0
    OUTPUT = 1
    MIDDLEWARE = 2
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema
        return core_schema.int_schema(ge=0)

class ConversionMode(aristaproto.Enum):
    DIRECT = 0
    SPLIT = 1
    MERGE = 2
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema
        return core_schema.int_schema(ge=0)

class ConflictPolicy(aristaproto.Enum):
    SKIP = 0
    PROMPT = 1
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema
        return core_schema.int_schema(ge=0)

@dataclass
class PluginInfo(aristaproto.Message):
    identifier: str = aristaproto.string_field(1)
    name: str = aristaproto.string_field(2)
    version: str = aristaproto.string_field(3)
    description: str = aristaproto.string_field(4)
    author: str = aristaproto.string_field(5)
    website: str = aristaproto.string_field(6)
    json_schema: str = aristaproto.string_field(7)
    file_format: str = aristaproto.string_field(8)
    """additional fields for io plugins"""
    suffixes: list[str] = aristaproto.string_field(9)
    icon_base64: str = aristaproto.string_field(10)
    ui_json_schema: str = aristaproto.string_field(11)

@dataclass
class PluginInfosRequest(aristaproto.Message):
    category: "PluginCategory" = aristaproto.enum_field(1)
    language: str = aristaproto.string_field(2)

@dataclass
class PluginInfosResponse(aristaproto.Message):
    values: list["PluginInfo"] = aristaproto.message_field(1)

@dataclass
class ConversionGroup(aristaproto.Message):
    group_id: str = aristaproto.string_field(1)
    file_contents: list[bytes] = aristaproto.bytes_field(2)

@dataclass
class ConversionRequest(aristaproto.Message):
    input_format: str = aristaproto.string_field(1)
    output_format: str = aristaproto.string_field(2)
    mode: "ConversionMode" = aristaproto.enum_field(3)
    max_track_count: int = aristaproto.int32_field(4)
    groups: list["ConversionGroup"] = aristaproto.message_field(5)
    input_options: str = aristaproto.string_field(6)
    output_options: str = aristaproto.string_field(7)
    middleware_options: dict[str, str] = aristaproto.map_field(
        8, aristaproto.TYPE_STRING, aristaproto.TYPE_STRING
    )

@dataclass
class SingleConversionResult(aristaproto.Message):
    group_id: str = aristaproto.string_field(1)
    completed: bool = aristaproto.bool_field(2)
    error_message: str = aristaproto.string_field(3)
    warning_messages: list[str] = aristaproto.string_field(4)

@dataclass
class VersionInfo(aristaproto.Message):
    version: str = aristaproto.string_field(1)

@dataclass
class MoveFileRequest(aristaproto.Message):
    group_id: str = aristaproto.string_field(1)
    force_overwrite: bool = aristaproto.bool_field(2)

@dataclass
class MoveFileResponse(aristaproto.Message):
    group_id: str = aristaproto.string_field(1)
    output_path: str = aristaproto.string_field(2)
    conflict_policy: "ConflictPolicy" = aristaproto.enum_field(3)

class ConversionBase(ServiceBase):
    async def plugin_infos(
        self, plugin_infos_request: "PluginInfosRequest"
    ) -> "PluginInfosResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
    async def convert(
        self, conversion_request: "ConversionRequest"
    ) -> AsyncIterator[SingleConversionResult]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
    async def version(self, version_info: "VersionInfo") -> "VersionInfo":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
    async def move_file(
        self, move_file_request: "MoveFileRequest"
    ) -> AsyncIterator[MoveFileResponse]:
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
    async def __rpc_plugin_infos(
        self,
        stream: "grpclib.server.Stream[PluginInfosRequest, PluginInfosResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.plugin_infos(request)
        await stream.send_message(response)
    async def __rpc_convert(
        self,
        stream: "grpclib.server.Stream[ConversionRequest, SingleConversionResult]",
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.convert,
            stream,
            request,
        )
    async def __rpc_version(
        self,
        stream: "grpclib.server.Stream[VersionInfo, VersionInfo]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.version(request)
        await stream.send_message(response)
    async def __rpc_move_file(
        self,
        stream: "grpclib.server.Stream[MoveFileRequest, MoveFileResponse]",
    ) -> None:
        request = await stream.recv_message()
        await self._call_rpc_handler_server_stream(
            self.move_file,
            stream,
            request,
        )
    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/LibreSVIP.Conversion/PluginInfos": grpclib.const.Handler(
                self.__rpc_plugin_infos,
                grpclib.const.Cardinality.UNARY_UNARY,
                PluginInfosRequest,
                PluginInfosResponse,
            ),
            "/LibreSVIP.Conversion/Convert": grpclib.const.Handler(
                self.__rpc_convert,
                grpclib.const.Cardinality.UNARY_STREAM,
                ConversionRequest,
                SingleConversionResult,
            ),
            "/LibreSVIP.Conversion/Version": grpclib.const.Handler(
                self.__rpc_version,
                grpclib.const.Cardinality.UNARY_UNARY,
                VersionInfo,
                VersionInfo,
            ),
            "/LibreSVIP.Conversion/MoveFile": grpclib.const.Handler(
                self.__rpc_move_file,
                grpclib.const.Cardinality.UNARY_STREAM,
                MoveFileRequest,
                MoveFileResponse,
            ),
        }
