# "$schema" = "../gen/schemas/desktop-schema.json"  # we do not support this feature yet
identifier = "default"
description = "Capability for the main window"
windows = ["main"]
permissions = [
    "core:default",
    "opener:default",
    "dialog:default",
    "pytauri:default",
    "core:window:allow-start-dragging",
    "core:window:allow-maximize",
    "core:window:allow-unmaximize",
    "core:window:allow-minimize",
    "core:window:allow-close",
    "clipboard-manager:allow-write-text",
]